syntax = "proto3";

package cart;

option go_package = "/cart";

service CartService{
  rpc AddItem(AddItemReq)returns(AddItemResp){};
  rpc GetCart(GetCartReq)returns(GetCartResp){};
  rpc EmptyCart(EmptyCartReq)returns(EmptyCartResp){};
}

message CartItem{
  int32 product_id = 1;
  int32 quantity = 2;
}

message AddItemReq{
  int32 user_id = 1;
  CartItem item = 2;
}

message AddItemResp{
}

message GetCartReq{
  int32 user_id = 1;
}

message GetCartResp{
  repeated CartItem items = 1;
}

message EmptyCartReq{
  int32 user_id = 1;
}

message EmptyCartResp{
}